blank_issues_enabled: true
contact_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/alexandre-goumain/
    about: Connect with me on LinkedIn for professional inquiries
  - name: Questions
    url: https://github.com/AlexandreGoumain/AlexandreGoumain/discussions
    about: Ask questions and discuss ideas
